Using Optimization.jl
MilkshakeForReal/DiffEqSensitivity.jl pull request #1
Opened 2022-06-19 12:55 UTC by Abhishek-1Bhatt

2022-06-19 20:00 UTC, MilkshakeForReal requested changes

2022-06-19 20:00 UTC, YichengDWu commented on docs/src/neural_ode/neural_gde.md
> +	ps = Optimization.solve(optprob, opt).minimizer
```julia
ERROR: The number of maxiters has to be a non-negative and non-zero number.
Stacktrace:
```

2022-06-19 20:00 UTC, YichengDWu commented on docs/src/neural_ode/neural_gde.md
> +import Optimization, OptimizationFlux
using Optimization
using OptimizationFlux: ADAM

2022-06-19 20:00 UTC, MilkshakeForReal commented on docs/src/neural_ode/neural_gde.md
Change the output here

2022-06-20 03:05 UTC, MilkshakeForReal commented on docs/src/neural_ode/neural_gde.md
> +	ps = Optimization.solve(optprob, opt).minimizer
Still not working
```julia
julia> solve(optprob,opt,maxiters=3)
ERROR: MethodError: no method matching copy(::NamedTuple{(:layer_1, :layer_2, :layer_3, :layer_4), Tuple{NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}, NamedTuple{(:layer_1, :layer_2), Tuple{NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}, NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}}}, NamedTuple{(), Tuple{}}, NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}}})
Closest candidates are:
  copy(::Union{SubArray{T, N, <:PooledArrays.PooledArray{T, R}}, PooledArrays.PooledArray{T, R, N}} where {T, N, R}) at C:\Users\Luffy\.julia\packages\PooledArrays\DXlaI\src\PooledArrays.jl:227
  copy(::DynamicPolynomials.Monomial) at C:\Users\Luffy\.julia\packages\DynamicPolynomials\juS7t\src\mono.jl:39
  copy(::LinearAlgebra.Diagonal{T, <:GPUArrays.AbstractGPUArray{T, N}}) where {T, N} at C:\Users\Luffy\.julia\packages\GPUArrays\Zecv7\src\host\linalg.jl:102
  ...
Stacktrace:
 [1] __solve(prob::OptimizationProblem{true, OptimizationFunction{true, Optimization.AutoZygote, var"#15#16", Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing}, NamedTuple{(:layer_1, :layer_2, :layer_3, :layer_4), Tuple{NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}, NamedTuple{(:layer_1, :layer_2), Tuple{NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}, NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}}}, NamedTuple{(), Tuple{}}, NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}}}, SciMLBase.NullParameters, Nothing, Nothing, Nothing, Nothing, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}}, opt::ADAM, data::Base.Iterators.Cycle{Tuple{Optimization.NullData}}; maxiters::Int64, callback::Function, progress::Bool, save_best::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ OptimizationFlux C:\Users\Luffy\.julia\packages\OptimizationFlux\cpWyO\src\OptimizationFlux.jl:19
 [2] solve(::OptimizationProblem{true, OptimizationFunction{true, Optimization.AutoZygote, var"#15#16", Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing}, NamedTuple{(:layer_1, :layer_2, :layer_3, :layer_4), Tuple{NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}, NamedTuple{(:layer_1, :layer_2), Tuple{NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}, NamedTuple{(:weilayer_2), Tuple{NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}, NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}}}, NamedTuple{(), Tuple{}}, NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}}}, SciMLBase.NullParameters, Nothing, Nothing, Nothing, Nothing, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}}, opt::ADAM, data::Base.Iterators.Cycle{Tuple{Optimization.NullData}}; maxiters::Int64, callback::Function, progress::Bool, save_best::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})   @ OptimizationFlux C:\Users\Luffy\.julia\packages\OptimizationFlux\cpWyO\src\OptimizationFlux.jl:19
 [2] solve(::OptimizationProblem{true, OptimizationFunction{true, Optimization.AutoZygote, var"#15#16", Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing}, NamedTuple{(:layer_1, :layer_2, :layer_3, :layer_4), Tuple{NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}, NamedTuple{(:layer_1, :layer_2), Tuple{NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}, NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}}}, NamedTuple{(), Tuple{}}, NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}}}, SciMLBase.NullParameters, Nothing, Nothing, Nothing, Nothing, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}}, ::ADAM; kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:maxiters,), Tuple{Int64}}})
   @ SciMLBase C:\Users\Luffy\.julia\packages\SciMLBase\koNdH\src\solve.jl:71
 [3] top-level scope   @ REPL[47]:1

   @ OptimizationFlux C:\Users\Luffy\.julia\packages\OptimizationFlux\cpWyO\src\OptimizationFlux.jl:19
 [2] solve(::OptimizationProblem{true, OptimizationFunction{true, Optimization.AutoZygote, var"#15#16", Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing}, NamedTuple{(:layer_1, :layer_2, :layer_3, :layer_4), Tuple{NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}, NamedTuple{(:layer_1, :layer_2), Tuple{NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}, NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}}}, NamedTuple{(), Tuple{}}, NamedTuple{(:weight, :bias), Tuple{CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}}}}}, SciMLBase.NullParameters, Nothing, Nothing, Nothing, Nothing, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}}, ::ADAM; kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:maxiters,), Tuple{Int64}}})   @ SciMLBase C:\Users\Luffy\.julia\packages\SciMLBase\koNdH\src\solve.jl:71
 [3] top-level scope
   @ REPL[47]:1
```
Also I'm sure if we need a for loop anymore. It seems the iteration is defined inside `solve`. In this case you need to put  `eval_loss_accuracy` inside a callback function

2022-06-20 03:05 UTC, MilkshakeForReal commented on docs/src/neural_ode/neural_gde.md
Sorry I meant add the printed output

2022-06-20 04:15 UTC, MilkshakeForReal commented on docs/src/neural_ode/neural_gde.md
>  ## Expected Output
add the printed output here

2022-06-20 04:15 UTC, MilkshakeForReal commented on docs/src/neural_ode/neural_gde.md
> +ps = Optimization.solve(optprob, opt, maxiters=1000, callback=callback).minimizer
We don't need to return `ps` anymore

`Optimization.solve(optprob, opt, maxiters=1000, callback=callback)`

2022-06-20 04:15 UTC, MilkshakeForReal commented on docs/src/neural_ode/neural_gde.md
> +Finally, we use the package `Optimization.solve` to learn the parameters `ps`. We run the training loop for `epochs` number of iterations.
Should `maxiters=epochs`?

2022-06-21 03:41 UTC, MilkshakeForReal commented
Can you try putting everything on the CPU on see if it works?

2022-06-21 04:07 UTC, Abhishek-1Bhatt commented
I won't be able to run it, the purpose of this pr was to make it use Optimization.jl, if there aren't any issues with that, then merge it. You'll have change the output after running it.

2022-06-21 04:19 UTC, MilkshakeForReal commented
I cant' change the output since it is not working. I gave a hint to debug it.

2022-06-21 04:23 UTC, MilkshakeForReal commented
You will have to change the output since you have it in your hand, if you can make it work on your computer

2022-06-21 04:35 UTC, Abhishek-1Bhatt commented
What is the error you're getting?

2022-06-21 04:47 UTC, MilkshakeForReal commented
Look it up in the review comments. I thought you had resolved it.

2022-06-21 04:58 UTC, MilkshakeForReal commented
Also, you don't reassign a value to a global variable
```julia
julia> a = 1
1

julia> function foo()
           @show a
           a = 2
           return nothing
       end
foo (generic function with 1 method)

julia> foo()
ERROR: UndefVarError: a not defined
Stacktrace:
 [1] macro expansion
   @ .\show.jl:1047 [inlined]
 [2] foo()
   @ Main .\REPL[12]:2
 [3] top-level scope
   @ REPL[13]:1
```
If you are not even aware of this, I'm curious how you got it running on your computer

2022-06-21 05:05 UTC, Abhishek-1Bhatt commented
As I said, I proposed the changes needed to make it use Optimization.jl, not to run it, I've got my own projects to work on, it's your project to make this doc example work, so you have to fix any minor issues with it.

2022-06-21 05:11 UTC, MilkshakeForReal commented
This is not my project. I opened my pr upon Chris's request. It is your organization's responsibility to make it work if you are a member of it. It is Chris who told you to transfer it to Optimization. I assume it is your job. If you are just a random guy I'm really sorry. I don't need to fix nothing since I always make sure my code runs before I submit a PR.

2022-06-21 05:13 UTC, closed without merging